#!/usr/bin/env bash
#
#   Release script for a generic Python project using pyproject.toml
#
#   Run this from the root directory of the project to be released.
#   Generally used in conjunction with the instructions in `pypi-release`:
#     https://github.com/cynic-net/pypi-release
#
#   This is currently a hack that still needs a good bit of manual work
#   and checking, but it helps.
#
set -Eeuo pipefail
trap 'echo 1>&2 "INTERNAL ERROR exitcode=$? line=$LINENO"' ERR

die() { local ec=$?; shift; echo 1>&2 "$(basename "$0"):" "$@"; exit $ec; }
warn() { echo 1>&2 "WARNING:" "$@"; }

####################################################################
#   Command line parsing

allow_dev=false
suppress_license_warnings=false
upload=false
while [[ $# -gt 0 ]]; do case "$1" in
    -d)         shift; allow_dev=true;;
    -L)         shift; suppress_license_warnings=true;;
    -u)         shift; upload=true;;
    -*)         die 2 "Unknown option: $1";;
    *)          break;;
esac; done
[[ $# -gt 0 ]] && die 2 "This program does not accept arguments."

####################################################################
#   Configuration validation

[[ -r pyproject.toml ]] || die 1 'pyproject.toml not found'
if grep '^version = ' pyproject.toml | grep -q dev; then
    if $allow_dev; then
        warn  'pyproject.toml version number includes "dev"'
    else
        die 1 'pyproject.toml version number includes "dev"'
    fi
fi
#   XXX test that doc/CHANGELOG.md includes version number above and
#   current date

####################################################################
#   Release process

echo '■ pactivate'
if [[ -r pactivate ]]; then
    reldir=.build/release
    . ./pactivate -q
elif [[ -r ../pactivate ]]; then
    reldir=../.build/release
    . ../pactivate -q
else
    die 3 "Cannot find pactivate or ../pactivate"
fi
pip -q install build twine toml

package_name=$(python3 -c '
import toml;
data = toml.load("pyproject.toml");
print(data["project"]["name"])
')
logfile="$package_name-build.log"

echo '■ cleaning previous builds'
mkdir -p "$reldir/dist"
rm -f "$reldir/$package_name"* "$reldir/dist/$package_name"*

if $suppress_license_warnings; then
    #   This is an assist during the conversion period from old to new
    #   license information format: see the README for details.
    #
    #   The warnings filters are `action:message:category:module:lineno`.
    #   Action is `ignore` and the message is a regexp from the list below. For
    #   the "category," which must be a class name that is a subclass of
    #   `Warning`, we cannot use `SetuptoolsDeprecationWarning` because it's
    #   not yet been imported when the interpreter starts up, so we use
    #   `UserWarning` whence the setuptools warning inherits. There's a similar
    #   issue with using `setuptools.warning` as the module, so we just don't
    #   bother.
    echo '▲ ━━━━━ suppressing license format warnings! ━━━━━'
    ignored_deprecation_warning_messages=(\
        'License classifiers are deprecated'
        '`project.license` as a TOML table is deprecated'
    )
    ignored_deprecation_warnings=$(printf \
        "ignore:%s:UserWarning," "${ignored_deprecation_warning_messages[@]}")
    export PYTHONWARNINGS=${ignored_deprecation_warnings%,}  # remove trailing comma
fi

#   If both the sdist and wheel builds are done in a single run,
#   `setuptools-scm` (if it's being used) will complain, 'ERROR
#   setuptools_scm._file_finders.git listing git files failed - pretending
#   there aren't any'. For some reason, just doing the two builds
#   separately fixes this.[1] You'd think you'd need to turn off isolation
#   as well[2], but apparently not.
#     [2]: https://stackoverflow.com/a/79313619/107294
#     [1]: https://github.com/pypa/setuptools-scm/issues/997#issuecomment-2612367874
echo "■ pyproject-build --sdist (output to $reldir/$logfile.sdist)"
pyproject-build --sdist --outdir "$reldir/dist/" >"$reldir/$logfile.sdist"
echo "■ pyproject-build --wheel (output to $reldir/$logfile.wheel)"
pyproject-build --wheel --outdir "$reldir/dist/" >"$reldir/$logfile.wheel"

echo '■ twine check'
twine check --strict "$reldir/dist"/*
if $upload; then
    echo '▲ twine upload'
    twine upload "$reldir/dist"/*
fi

echo '■ OK'
